WebThueXe/WebThueXe/Models/car.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.rentDetails = new HashSet<rentDetail>();
        }
    
        public int id_cars { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_seat { get; set; }
        public Nullable<bool> Hot { get; set; }
        public string describe { get; set; }
        public string consume { get; set; }
        public string status { get; set; }
    
        public virtual seat seat { get; set; }
        public virtual type type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentDetail> rentDetails { get; set; }
    }
}

WebThueXe/WebThueXe/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using WebThueXe.Models;

namespace WebThueXe.Controllers
{
    public class CarsController : Controller
    {
        ThueXeEntities db = new ThueXeEntities();
        // GET: Cars
        public ActionResult Index(string Name, int Type = 0)
        {
            var typees = from i in db.types select i;
            ViewBag.Type = new SelectList(typees, "id_type", "type1");
            var names = db.cars.Include(j => j.type);
            if (!string.IsNullOrEmpty(Name))
            {
                names = names.Where(i => i.name.Contains(Name));
            }
            if (Type != 0)
            {
                names = names.Where(j => j.id_type == Type);
            }
            return View(names.ToList());
        }
        public ActionResult CarList_Home()
        {
            var items = db.cars.Include(j => j.type);
            items = items.Where(i => (bool)i.IsActive).Where(j => (bool)j.Hot);
            return PartialView("CarsList", items.ToList());
        }
        public ActionResult Details(int? idx)
        {
            if (idx == null) return HttpNotFound();
            var currentCar = db.cars.Find(idx);

            if (currentCar == null) return HttpNotFound();

            // Lấy danh sách xe liên quan (cùng loại nhưng không phải là xe hiện tại)
            var relatedCars = db.cars.Where(c => c.id_type == currentCar.id_type && c.id_cars != currentCar.id_cars).ToList();

            ViewBag.RelatedProducts = relatedCars;

            return View("Detail", currentCar);

        }
    }
}

WebThueXe/WebThueXe/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebThueXe.Models;

namespace WebThueXe.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        ThueXeEntities db = new ThueXeEntities();
        public ActionResult Index()
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            return View(giohang);
        }


        public ActionResult AddCart(int id)
        {
            if (Session["giohang"] == null)
            {
                Session["giohang"] = new List<CartItem>();
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;

            if (giohang.FirstOrDefault(m => m.id_cars == id) == null) // ko co sp nay trong gio hang
            {
                car sp = db.cars.Find(id);

                CartItem newItem = new CartItem()
                {
                    id_cars = id,
                    name = sp.name,
                    SoLuong = 1,
                    image = sp.image,
                    price = (int)sp.price,

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.id_cars == id);
                cardItem.SoLuong++;
            }
            return Redirect(url: Request.UrlReferrer.ToString());
            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            //return RedirectToAction("Details", "Cars", new { idx = id });
        }
        public RedirectToRouteResult SuaSoLuong(int SanPhamID, int soluongmoi)
        {
            // tìm carditem muon sua
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemSua = giohang.FirstOrDefault(m => m.id_cars == SanPhamID);
            if (itemSua != null)
            {
                itemSua.SoLuong = soluongmoi;
            }
            return RedirectToAction("Index");

        }

        public RedirectToRouteResult XoaKhoiGio(int SanPhamID)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemXoa = giohang.FirstOrDefault(m => m.id_cars == SanPhamID);
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(FormCollection frm)
        {
            // Kiểm tra giỏ hàng không trống
            if (Session["giohang"] == null || !(Session["giohang"] is List<CartItem> carts) || !carts.Any())
            {
                ModelState.AddModelError("", "Giỏ hàng không tồn tại hoặc đã trống.");
                return View();
            }

            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    rent rent = new rent()
                    {
                        name = frm["inputUsername"],
                        phone = frm["inputPhone"],
                        mail = frm["inputEmail"],
                        note = frm["inputNote"],
                        date = DateTime.Now,
                        // Thêm mã KH từ session nếu người dùng đã đăng nhập
                        maKH = (Session["KH"] as KhachHang)?.maKH
                    };
                    db.rents.Add(rent);
                    db.SaveChanges();
                    foreach (CartItem item in carts)
                    {
                        rentDetail rentDetail = new rentDetail()
                        {
                            id_rent = rent.id_rent,
                            id_cars = item.id_cars,
                            amount = item.SoLuong,
                            maKH = rent.maKH // Sử dụng maKH từ đối tượng rent
                        };
                        db.rentDetails.Add(rentDetail);
                    }
                    db.SaveChanges();
                    dbContextTransaction.Commit();


                    Session.Remove("giohang");
                    return RedirectToAction("RentSuccess");
                }
                catch (Exception ex)
                {
                    // Log the error
                    dbContextTransaction.Rollback();
                    ModelState.AddModelError("", "Có lỗi xảy ra khi xử lý đơn hàng của bạn: " + ex.Message);
                    // Optionally, pass the exception data to the Error view
                    return View("Error", ex);
                }
            }
        }

    }
}

WebThueXe/WebThueXe/Views/Cars/CarsList.cshtml
    @model IEnumerable<WebThueXe.Models.car>
@foreach (var item in Model)
{
    <div class="item">
        <div class="car-wrap rounded ftco-animate">
            <div class="img rounded d-flex align-items-end" style="background-image: url(@item.image);">
            </div>
            <div class="text">
                <h2 class="mb-0"><a href="@Url.Action("Details", "Cars", new {idx =  item.id_cars})">@item.name</a></h2>
                <div class="d-flex mb-3">
                    <span class="cat">@item.type.type1</span>
                    <p class="price ml-auto">@item.price <span>/giờ</span></p>
                </div>
                <p class="d-flex mb-0 d-block"><a href="@Url.Action("AddCart", "Cart", new {id =  item.id_cars})" class="btn btn-primary py-2 mr-1">Thêm vào giỏ</a> @Html.ActionLink("Chi tiết", "Details", new { idx = item.id_cars }, new { @class = "btn btn-secondary py-2 ml-1" })</p>
            </div>
        </div>
    </div>
}

WebThueXe/WebThueXe/Views/Cars/Detail.cshtml
@model WebThueXe.Models.car
@{
    ViewBag.Title = "Car_Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('../../content/images/bg_3.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs"><span class="mr-2"><a href="~/Home">Trang chủ <i class="ion-ios-arrow-forward"></i></a></span> <span>Xe <i class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-3 bread">Chi tiết xe</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-car-details">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="car-details">
                    <div class="img rounded" style="background-image: url(@Model.image);"></div>
                    <div class="text text-center">
                        <span class="subheading">@Model.type.type1</span>
                        <h2>@Model.name</h2>
                        <a href="@Url.Action("AddCart", "Cart", new {id = Model.id_cars})" class="btn btn-primary py-2 mr-1">Thêm vào giỏ</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md d-flex align-self-stretch ftco-animate">
                <div class="media block-6 services">
                    <div class="media-body py-md-4">
                        <div class="d-flex mb-3 align-items-center">
                            <div class="icon d-flex align-items-center justify-content-center">
                                <span class="flaticon-diesel"></span>
                            </div>
                            <div class="text">
                                <h3 class="heading mb-0 pl-3">
                                    Tiêu hao
                                    <span>@Model.consume mỗi 100km</span>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="media block-6 services">
                    <div class="media-body py-md-4">
                        <div class="d-flex mb-3 align-items-center">
                            <div class="icon d-flex align-items-center justify-content-center">
                                <span class="flaticon-car"></span>
                            </div>
                            <div class="text">
                                <h3 class="heading mb-0 pl-3">
                                    Tình trạng
                                    <span>@Model.status</span>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 pills">
                <div class="bd-example bd-example-tabs">
                    <div class="d-flex justify-content-center">
                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="pills-manufacturer-tab" data-toggle="pill" href="#pills-manufacturer" role="tab" aria-controls="pills-manufacturer" aria-expanded="true">Mô tả</a>
                            </li>
                        </ul>
                    </div>
                    <p>@Html.Raw(Model.describe)</p>
                </div>
            </div>
        </div>
        <h3>Sản phẩm liên quan</h3>
        <div class="row">
            @foreach (var relatedProduct in ViewBag.RelatedProducts as List<WebThueXe.Models.car>)
            {
                <div class="car-wrap rounded ftco-animate" style="gap:20px">
                    <a href="@Url.Action("Details", "Cars", new { idx = relatedProduct.id_cars })" class="img rounded d-flex align-items-end" style="background-image: url('@relatedProduct.image');">
                        <img src="@relatedProduct.image" alt="@relatedProduct.name" onclick="redirectToProductDetail(@relatedProduct.id_cars)"
                             class="img rounded d-flex align-items-end" style="justify-items:center;gap:20px" />
                        <!-- Bỏ img tag và sử dụng background-image cho thẻ a -->
                    </a>
                    <div class="text">
                        <a href="@Url.Action("Details", "Cars", new { idx = relatedProduct.id_cars })">@relatedProduct.name</a>
                        <span>@(((decimal)relatedProduct.price).ToString("N0"))₫</span>
                    </div>
                </div>
            }

        </div>
        <style>
            .row {
                display: flex;
                flex-wrap: wrap;
                margin-right: -15px; /* Điều chỉnh nếu cần */
                margin-left: -15px; /* Điều chỉnh nếu cần */
            }

            .car-wrap {
                margin: 10px; /* Thêm khoảng cách xung quanh mỗi car-wrap */
                flex: 0 0 calc(30% - 20px); /* Chia đều không gian cho mỗi car-wrap, 20px là tổng của margin-left và margin-right */
                box-sizing: border-box;
            }

            .img {
                width: 100%; /* Chiều rộng hình ảnh sẽ chiếm toàn bộ chiều rộng của car-wrap */
                height: auto; /* Để giữ tỉ lệ hình ảnh */
                display: block; /* Đảm bảo hình ảnh không có khoảng trống bên dưới */
            }

            .car-wrap p,
            .car-wrap span {
                text-align: center; /* Căn giữa text dưới hình ảnh */
                display: block; /* Đảm bảo text hiển thị trên dòng mới */
            }
        </style>
</section>

WebThueXe/WebThueXe/Views/Cars/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('../../content/images/bg_3.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs"><span class="mr-2"><a href="~/Home">Trang chủ <i class="ion-ios-arrow-forward"></i></a></span> <span>Xe <i class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-3 bread">Chọn xe của bạn</h1>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section bg-light">
    <div class="container">
        @using (Html.BeginForm("Index", "Cars", FormMethod.Get))
        {
            <div class="timkiemm">
                @Html.TextBox("Name", null, new { @placeholder = "Nhập tên...", @class = "timkiem" })
                @Html.DropDownList("Type", null, "All", new { @class = "luachon" })
                <input type="submit" class="btn btn-secondary py-3 px-4 " value="Tìm kiếm" />
            </div>
        }
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="car-wrap rounded ftco-animate">
                        <div class="img rounded d-flex align-items-end" style="background-image: url(@item.image);">
                        </div>
                        <div class="text">
                            <h2 class="mb-0"><a href="@Url.Action("Details", "Cars", new {idx =  item.id_cars})">@item.name</a></h2>
                            <div class="d-flex mb-3">
                                <span class="cat">@item.type.type1</span>
                                <p class="price ml-auto">@item.price <span>/giờ</span></p>
                            </div>
                            <p class="d-flex mb-0 d-block"><a href="@Url.Action("AddCart", "Cart", new {id =  item.id_cars})" class="btn btn-primary py-2 mr-1">Thêm vào giỏ</a> @Html.ActionLink("Chi tiết", "Details", new { idx = item.id_cars }, new { @class = "btn btn-secondary py-2 ml-1" })</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>