WebThueXe/WebThueXe/Models/employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id_employee { get; set; }
        public string account { get; set; }
        public string pass { get; set; }
        public string name { get; set; }
        public Nullable<bool> fulControl { get; set; }
    }
}

WebThueXe/WebThueXe/Areas/Admin/Controllers/employeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using WebThueXe.Models;

namespace WebThueXe.Areas.Admin.Controllers
{
    public class employeesController : BaseController
    {

        // GET: Admin/employees
        private ThueXeEntities db = new ThueXeEntities();
        public ActionResult Index()
        {
            return View(db.employees.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_employee,account,pass,name,fulControl")] employee employee)
        {
            if (ModelState.IsValid)
            {
                db.employees.Add(employee);
                db.SaveChanges();
                ThongBao("Thêm thành công!!!", "success");
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            db.employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            db.employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult changeControl(int? id)
        {
            employee employee = db.employees.Find(id);
            if (employee.fulControl == true)
            {
                employee.fulControl = false;
            }
            else
            {
                employee.fulControl = true;
            }
            db.SaveChanges();
            return Json(new
            {
                status = employee.fulControl
            });

        }
        public ActionResult rename(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee nv = db.employees.Find(id);
            if (nv == null)
            {
                return HttpNotFound();
            }
            return View("Rename", nv);
        }
        [HttpPost]
        public ActionResult rename(int? id, string namenew)
        {
            try
            {
                employee nv = db.employees.Find(id);
                nv.name = namenew;
                db.SaveChanges();
                ThongBao("Đổi tên thành công :v", "success");
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View("Error");
            }
        }
        public ActionResult AdminName()
        {
            var admin = Session["UserAdmin"] as WebThueXe.Models.employee;
            int id = admin.id_employee;
            var item = db.employees.Find(id);
            return PartialView("AdminName", item);
        }

        public ActionResult ChangePsw(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee nv = db.employees.Find(id);
            if (nv == null)
            {
                return HttpNotFound();
            }
            return View(nv);
        }
        [HttpPost]
        public ActionResult ChangePsw(int? id, string pswOld, string pswNew)
        {
            try
            {
                employee nv = db.employees.Find(id);
                if (nv.pass == pswOld)
                {
                    // Kiểm tra mật khẩu mới
                    var hasNumber = new Regex(@"[0-9]+");
                    var hasUpperChar = new Regex(@"[A-Z]+");
                    var hasMinimum6Chars = new Regex(@".{6,}");
                    var hasSpecialChar = new Regex(@"[!@#$%^&*()_+=\[{\]};:<>|./?,-]");

                    if (!hasNumber.IsMatch(pswNew) || !hasUpperChar.IsMatch(pswNew) || !hasMinimum6Chars.IsMatch(pswNew) || !hasSpecialChar.IsMatch(pswNew))
                    {
                        ThongBao("Mật khẩu phải chứa ít nhất 6 ký tự, bao gồm 1 chữ in hoa và 1 ký tự đặc biệt :v", "error");
                        return RedirectToAction("ChangePsw", new { id = id });
                    }

                    nv.pass = pswNew;
                    db.SaveChanges();
                    ThongBao("Đổi mật khẩu thành công :v", "success");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ThongBao("Mật khẩu hiện tại chưa chính xác :v", "error");
                    return RedirectToAction("ChangePsw", new { id = id });
                }
            }
            catch
            {
                return View("Error");
            }
        }
        [HttpPost]
        public JsonResult VerifyCurrentPassword(int id, string currentPassword)
        {
            var employee = db.employees.Find(id);
            if (employee != null && employee.pass == currentPassword)
            {
                return Json(true);
            }
            return Json(false);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebThueXe/WebThueXe/Areas/Admin/Views/employees/AdminName.cshtml
@model WebThueXe.Models.employee

<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Model.name</span>
        <img class="img-profile rounded-circle"
             src="~/Content/Admin/img/undraw_profile.svg">
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
         aria-labelledby="userDropdown">
        <a class="dropdown-item" href="@Url.Action("rename","employees",new {id = Model.id_employee})">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Đổi tên
        </a>
        <a class="dropdown-item" href="@Url.Action("ChangePsw","employees",new {id = Model.id_employee})">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Đổi mật khẩu
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="~/Admin/Logout" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Đăng xuất
        </a>
    </div>
</li>

WebThueXe/WebThueXe/Areas/Admin/Views/employees/ChangePsw.cshtml
@model WebThueXe.Models.employee
@{
    ViewBag.Title = "ChangePsw";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

@using (Html.BeginForm("ChangePsw", "employees", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card mb-4">
        <div class="card-header" style="color: #0061f2"><b>Đổi mật khẩu</b></div>
        <div class="card-body">
            <input type="number" hidden name="id" value="@Model.id_employee" />
            <!-- Form Group (current password)-->
            <div class="mb-3">
                <label class="small mb-1" for="currentPassword">Mật khẩu hiện tại</label>
                <input class="form-control" id="currentPassword" name="pswOld" type="password" placeholder="Nhập mật khẩu hiện tại ...">
                <span id="currentPasswordStatus"></span>
            </div>
            <!-- Form Group (new password)-->
            <div class="mb-3">
                <label class="small mb-1" for="password">Mật khẩu mới</label>
                <input class="form-control" id="password" required onkeyup='check();' type="password" placeholder="Nhập mật khẩu mới ...">
                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
            </div>
            <!-- Form Group (confirm password)-->
            <div class="mb-3">
                <label class="small mb-1" for="confirm_password">Xác nhận mật khẩu</label>
                <input class="form-control" id="confirm_password" name="pswNew" required onkeyup='check();' type="password" placeholder="Xác nhận mật khẩu mới ...">
            </div>
            <button class="btn btn-primary" id="changepsw" disabled type="submit">Xác nhận</button>
        </div>
    </div>
}
<script>
    var check = function () {
        if (document.getElementById('password').value ==
            document.getElementById('confirm_password').value) {
            document.getElementById('changepsw').disabled = false;

        } else {
            document.getElementById('changepsw').disabled = true;

        }
    }
</script>
<script>
    $(document).ready(function () {
        var verifyPasswordUrl = '@Url.Action("VerifyCurrentPassword", "employees")';
        $('#currentPassword').keyup(function () {
            var currentPassword = $(this).val();
            var id = $('input[name="id"]').val();
            if (currentPassword.length > 0) {
                $.post(verifyPasswordUrl, { id: id, currentPassword: currentPassword }, function (isCorrect) {
                    $('#currentPasswordStatus').html(isCorrect ? '✔️' : '✖️');
                    $('#currentPasswordStatus').css('color', isCorrect ? 'green' : 'red');
                });
            } else {
                $('#currentPasswordStatus').html('');
            }
        });
    });
</script>

WebThueXe/WebThueXe/Areas/Admin/Views/employees/Create.cshtml
@model WebThueXe.Models.employee

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm tài khoản quản trị</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="pass" name="pass" type="password" required>                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

WebThueXe/WebThueXe/Areas/Admin/Views/employees/Index.cshtml
@model IEnumerable<WebThueXe.Models.employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}
@{
    var admin = Session["UserAdmin"] as WebThueXe.Models.employee;
}
@if (admin.fulControl == true)
{
    <h2>Quản lý nhân viên</h2>

    <p>
        <a href="@Url.Action("Create","employees")" class="btn btn-info btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Thêm tài khoản nhân viên</span>
        </a>
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.account)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
               Hành động
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.account)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
               
                <td>
                    <a href="@Url.Action("DeleteConfirmed","employees", new { id = item.id_employee })" onclick="return confirm('Bạn có chắc chắn muốn xoá?');" class="btn btn-danger btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-trash"></i>
                        </span>
                        <span class="text">Xoá</span>
                    </a>
                </td>
            </tr>
        }

    </table>
}
else
{
    <h2 style="text-align:center;color:red">Bạn không đủ quyền truy cập phần này!!!</h2>
}

@section scripts{
    <script>
        $(document).ready(function () {
            $(".btn-custom").off('click').on('click', function (e) {
                e.preventDefault();
                var id = $(this).data('id');
                $.ajax({
                    url: "/Admin/employees/changeControl",
                    data: { id: id },
                    type: "POST",
                    success: function (data) {
                        if (data.status) {
                            window.location.reload();
                        }
                        else {
                            window.location.reload();
                        }
                    }
                });
            })

        })
    </script>
}

WebThueXe/WebThueXe/Areas/Admin/Views/employees/Rename.cshtml
@model WebThueXe.Models.employee
@{
    ViewBag.Title = "Rename";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}

<div class="card mb-4">
    <div class="card-header" style="color: #0061f2"><b>Đổi tên</b></div>
    <div class="card-body">
            @using (Html.BeginForm("rename","employees",FormMethod.Post))
            {
                <div class="mb-3">
                    <label class="small mb-1" for="confirmPassword">Nhập tên mới...</label>
                    <input type="number" hidden name="id" value="@Model.id_employee" />
                    <input class="form-control" required name="namenew" type="text" placeholder="Nhập tên bạn muốn đổi ở đây...">
                </div>
                <button class="btn btn-primary" type="submit">Xác nhận</button>
            }
    </div>
</div>